version: "2"
services:
  node:
    build:
      context: .
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "4040:4040"
    expose:
      - 4040
  postgres:
    restart: always
    image: postgres:9.6.2-alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=xscraper
      - POSTGRES_PASSWORD=xscraper
      - POSTGRES_DB=xscraper
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
volumes:
    postgresql-volume:
      driver: 'local'